homepage:
    path: /
    controller: App\Controller\HomeController
    host:     "{_locale}.wowaffixes.info"
homepage_nolocale:
    path: /
    controller: App\Controller\HomeController
    requirements:
        _locale: en|fr|de|es|it|pt|ru|ko|cn|www